interface CompetitorData {
  name: string;
  url: string;
  summary: string;
  pricing: string;
  recentMoves: string;
  hiringSignals: string;
  keyDifferentiator: string;
  threatLevel: string;
}

interface ReportData {
  startup_name: string;
  startup_url: string;
  analyzed_at: string;
  competitors: CompetitorData[];
  market_intelligence: string[];
  recommendations: string[];
}

const THREAT_COLORS = {
  high: { bg: "#fecaca", text: "#dc2626", border: "#f87171" },
  medium: { bg: "#fef3c7", text: "#d97706", border: "#fbbf24" },
  low: { bg: "#d1fae5", text: "#059669", border: "#34d399" },
};

export function generateReportHTML(report: ReportData): string {
  const date = new Date(report.analyzed_at).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  const competitorsHtml = report.competitors
    .map(c => {
      const level = (c.threatLevel?.toLowerCase() || "low") as keyof typeof THREAT_COLORS;
      const colors = THREAT_COLORS[level] || THREAT_COLORS.low;
      return `
        <div style="border:1px solid ${colors.border};border-radius:12px;padding:20px;margin-bottom:16px;background:${colors.bg}10;">
          <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;">
            <h3 style="margin:0;font-size:18px;color:#1a1a1a;">${c.name}</h3>
            <span style="background:${colors.bg};color:${colors.text};padding:4px 12px;border-radius:20px;font-size:11px;font-weight:bold;text-transform:uppercase;">${c.threatLevel}</span>
          </div>
          <p style="color:#555;font-size:14px;margin:0 0 12px;">${c.summary}</p>
          <table style="width:100%;font-size:13px;color:#666;">
            <tr><td style="padding:4px 0;"><strong>Pricing:</strong> ${c.pricing}</td><td style="padding:4px 0;"><strong>Differentiator:</strong> ${c.keyDifferentiator}</td></tr>
            <tr><td style="padding:4px 0;"><strong>Hiring:</strong> ${c.hiringSignals}</td><td style="padding:4px 0;"><strong>Recent:</strong> ${c.recentMoves}</td></tr>
          </table>
        </div>`;
    })
    .join("");

  const recommendationsHtml = report.recommendations
    .map((r, i) => `<li style="margin-bottom:8px;color:#333;font-size:14px;">${r}</li>`)
    .join("");

  const intelligenceHtml = report.market_intelligence
    .map(m => `<li style="margin-bottom:6px;color:#555;font-size:14px;">${m}</li>`)
    .join("");

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; }
  h1 { font-size: 28px; margin-bottom: 4px; }
  h2 { font-size: 20px; color: #333; margin-top: 32px; border-bottom: 2px solid #eee; padding-bottom: 8px; }
</style></head>
<body>
  <h1>Competitor Intel: ${report.startup_name}</h1>
  <p style="color:#888;font-size:13px;margin-bottom:32px;">${report.startup_url} &middot; ${date}</p>

  <h2>Competitors (${report.competitors.length})</h2>
  ${competitorsHtml}

  ${report.recommendations.length > 0 ? `<h2>Recommendations</h2><ol>${recommendationsHtml}</ol>` : ""}
  ${report.market_intelligence.length > 0 ? `<h2>Market Intelligence</h2><ul>${intelligenceHtml}</ul>` : ""}

  <hr style="margin-top:40px;border:none;border-top:1px solid #eee;">
  <p style="color:#aaa;font-size:11px;text-align:center;margin-top:16px;">
    Generated by Competitor Intel &middot; Powered by Firecrawl, Claude, Reducto, MongoDB, Resend
  </p>
</body>
</html>`;
}
